package dax.api_lib.models;

public enum WalkerPreferences {
    SPIRIT_TREE_ETCETERIA,
    SPIRIT_TREE_PORT_SARIM,
    SPIRIT_TREE_BRIMHAVEN,
    SPIRI_TREE_HOSIDIUS,
    SPIRIT_TREE_FARMING_GUILD,
    SPIRIT_TREE_POH,

    MAGIC_MUSHTREE_HOUSE_ON_THE_HILL,
    MAGIC_MUSHTREE_MUSHROOM_MEADOW,
    MAGIC_MUSHTREE_STICKY_SWAMP,
    MAGIC_MUSHTREE_VERDANT_VALLEY;

}
